### ISSUE TITLE
converting infdev '.mclevel' to infdev 'world' files

### ISSUE THREAD

**Issue by csBlackWolf** [molneya/indev-level-converter#6]
Hallo.

I want to convert a level save from the inf-20100325 (.mclevel) to world files for inf-20100330.

I was hoping i could do this with your script, but it is just throwing errors.

![grafik](https://user-images.githubusercontent.com/30509936/139345326-aaf3bcc1-1e77-4387-9c39-1589bfec3977.png)

Would it be possible to do this somehow?

---

System Infos:

> Windows 10 Home (20H2)

> Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32

> pip version 20.2.4

> Requirement already satisfied: nbtlib in c:\users\fwerh\appdata\local\programs\python\python39\lib\site-packages (2.0.1)

> Requirement already satisfied: numpy in c:\users\fwerh\appdata\local\programs\python\python39\lib\site-packages (from nbtlib) (1.21.3)

**Comment by molneya** [comment]
what is inf-20100325? that isnt an indev version, nor a saveable version as far as i know. need some more information here

also sorry for the late reply, not really checking here very often.

**Comment by csBlackWolf** [comment]
I was speaking from this version: [Infdev 20100325](https://minecraft.fandom.com/wiki/Java_Edition_Infdev_20100325)
It semms to be possible to save this Level as a '.mclevel' file. However, I just noticed that the saved files are empty (0 Bytes). So it's not possible anyway. Sorry for this and thanks for your time. 😀
