### ISSUE TITLE
paintings cause error when world saves after conversion

### ISSUE THREAD

**Issue by Ratonguerrier** [molneya/indev-level-converter#9]
Hi, I created an indev world in the Indev-20100223 version.
The size of the world is 64x512x512.

When I try to convert it, it gives me the error <Could not convert cacaWorld.mclevel: 'int' object has no attribute 'tag_id'>

I may like even have the world file, but when I run it in an infdev, alpha or beta version, it gets corrupted, and my builds get destroyed.

I would like to know where the problem comes from, if you can help me, thank you.

**Comment by molneya** [comment]
guessing this is an issue with nbtlib. make sure you have the right version of that installed (see readme). i may get around to updating this tool again to update it to the latest version of nbtlib.

**Comment by Ratonguerrier** [comment]
I just reinstalled python 3.10.3, and I reinstalled nbtlib 1.12.1.
To test, I created a second indev world which has the size of 64x512x512.
I convert it, and I see that it works very well. So I try to convert my world with my builds, but, it's always the same problem.

If you have time, I send you the world that can't be converted, I think it's corrupt. 

[World1.zip](https://github.com/molneya/indev-level-converter/files/8310997/World1.zip)

**Comment by molneya** [comment]
Testing myself i see that it actually converts fine but fails on actually saving the world. the chunks at (10, 16), (10, 17) and (11, 17) in particular fail for some reason. Loading the world up reveals that paintings were stored up in that area and removing them fixed the problem. so this is actually some issue with paintings not converting correctly.

your world isn't corrupt, just remove the paintings before conversion and add them once you are in an alpha save format version as a temporary solution

**Comment by Ratonguerrier** [comment]
Hi, Thanks for testing! I had a room with paintings, I was finally able to update my survival world!

**Comment by molneya** [comment]
fixed. better late then never
